"""Autoresearch iteration loop — the core learning engine.

Adapts Karpathy's autoresearch pattern for ontology refinement:
- ontology/ is the ONE modifiable workspace (like train.py)
- evaluate.py is READ-ONLY eval (like prepare.py)
- neo_score is the single scalar metric (like val_bpb)
- iterations.tsv is the experiment log (like results.tsv)
- LOOP FOREVER until plateau or user interrupts

Each iteration:
1. Read current state + past iterations
2. Identify ONE highest-impact improvement
3. APPLY the change to ontology/ (actually write files)
4. Eval → neo_score
5. Keep if improved, revert if not
6. Log to iterations.tsv
7. Repeat
"""
from __future__ import annotations

import csv
import subprocess
import sys
import yaml
from datetime import datetime, timezone
from pathlib import Path

from pipeline.evaluate import compute_neo_score, KNOWN_FRAUD_PATTERNS


# ---------------------------------------------------------------------------
# Rule templates for autonomous generation
# ---------------------------------------------------------------------------

RULE_TEMPLATES = {
    # --- Existing rules that can be regenerated ---
    "stale-evidence": {
        "id": "screenshot-date-vs-photo-date",
        "name": "Screenshot freshness check",
        "description": "The transaction query date range shown in the app should be recent relative to the photo date. Stale screenshots suggest reuse from a previous application.",
        "condition": "photo_date - transaction_query_end_date > 30_days",
        "action": "flag_stale_screenshot",
        "severity": "warning",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "temporal",
    },
    "round-salary": {
        "id": "round-number-deposit",
        "name": "Suspiciously round deposit amounts",
        "description": "Salary amounts that are perfectly round may indicate staged deposits. Real salaries typically have non-round amounts after tax/insurance deductions.",
        "condition": "salary_transaction.amount % 1_000_000 == 0 AND salary_transaction.amount > 0",
        "action": "flag_round_salary",
        "severity": "info",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "income",
        "note": "High false positive rate — some employers do pay round amounts.",
    },
    "inflated-balance": {
        "id": "balance-vs-salary-ratio",
        "name": "Balance to salary ratio check",
        "description": "If account balance is very high relative to demonstrated salary, the balance may have been temporarily inflated for the verification.",
        "condition": "bank_account.balance > income_profile.average_monthly_salary * 6",
        "action": "flag_inflated_balance",
        "severity": "info",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "balance",
    },
    # --- New rules for known gaps ---
    "device-reuse": {
        "id": "device-reuse-check",
        "name": "Cross-applicant device reuse detection",
        "description": "Flag when the same phone device model and type appears across different applicant packages, suggesting manufactured evidence.",
        "condition": "count(packages_with_same_device_model) > 1",
        "action": "flag_device_reuse",
        "severity": "critical",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "cross-package",
    },
    "employee-volume": {
        "id": "employee-volume-check",
        "name": "Employee processing volume anomaly",
        "description": "Flag when a single VPBank employee processes an abnormally high number of applications in a short period.",
        "condition": "employee.applications_per_week > 20",
        "action": "flag_employee_volume",
        "severity": "warning",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "cross-package",
    },
    "photo-manipulation": {
        "id": "photo-manipulation-check",
        "name": "Screenshot manipulation detection",
        "description": "Flag when verification photos show signs of digital editing: inconsistent fonts, compression artifacts around text, misaligned UI elements.",
        "condition": "verification_photo.manipulation_score > 0.7",
        "action": "flag_photo_manipulation",
        "severity": "critical",
        "source": "Auto-generated by Neo iteration loop",
        "domain": "visual",
    },
}

# Templates for missing ontology files
FILE_TEMPLATES = {
    "ONTOLOGY.md": "# Domain Ontology\n\n## Purpose\nThis ontology encodes domain expertise for AI agent consumption.\n\n## Epistemic Status\ndraft\n",
    "INVENTORY.md": "# Data Sources Inventory\n\n## Sources\n*(no sources cataloged yet)*\n",
    "docs/gaps.md": "# Knowledge Gaps\n\n<!-- Reported by Neo.Architect gap sensing -->\n",
    "docs/contradictions.md": "# Contradiction Register\n\n<!-- Tensions detected during ontology construction -->\n",
}


# ---------------------------------------------------------------------------
# Apply improvement (THE KEY FUNCTION — actually writes files)
# ---------------------------------------------------------------------------

def apply_improvement(ontology_path: Path, improvement: dict) -> bool:
    """Apply an improvement to the ontology. Returns True if a change was made."""
    action = improvement.get("action", "")

    if action == "add_rule":
        return _apply_add_rule(ontology_path, improvement)
    elif action == "design_new_rule":
        return _apply_design_new_rule(ontology_path, improvement)
    elif action == "create_file":
        return _apply_create_file(ontology_path, improvement)
    elif action == "fix_empty_yaml":
        return _apply_fix_empty_yaml(improvement)
    elif action == "add_entity_id":
        return _apply_add_entity_id(improvement)
    elif action == "add_rule_severity":
        return _apply_add_rule_severity(improvement)
    elif action == "fix_yaml_syntax":
        return False  # Can't auto-fix syntax errors
    elif action == "review_for_removal":
        return False  # Simplification needs human judgment
    else:
        return False


def _apply_add_rule(ontology_path: Path, improvement: dict) -> bool:
    """Add a missing rule that has a known template."""
    pattern_id = improvement.get("pattern_id", "")
    template = RULE_TEMPLATES.get(pattern_id)
    if not template:
        return False

    rules_file = ontology_path / "rules" / "fraud-detection-rules.yaml"
    if not rules_file.exists():
        return False

    data = yaml.safe_load(rules_file.read_text())
    if not isinstance(data, dict) or "rules" not in data:
        return False

    # Check not already added
    existing_ids = {r.get("id") for r in data["rules"]}
    if template["id"] in existing_ids:
        return False

    data["rules"].append(dict(template))
    rules_file.write_text(yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False))
    return True


def _apply_design_new_rule(ontology_path: Path, improvement: dict) -> bool:
    """Design and add a new rule for an uncovered fraud pattern."""
    pattern_id = improvement.get("pattern_id", "")
    template = RULE_TEMPLATES.get(pattern_id)
    if not template:
        # No template — add a placeholder rule to gaps.md instead
        gaps_file = ontology_path / "docs" / "gaps.md"
        if gaps_file.exists():
            content = gaps_file.read_text()
            gap_marker = f"## Gap: Rule needed for {pattern_id}"
            if gap_marker not in content:
                content += f"\n{gap_marker}\n- **Reported by:** Neo iteration loop\n- **Priority:** HIGH\n- **Status:** OPEN\n"
                gaps_file.write_text(content)
                return True
        return False

    return _apply_add_rule(ontology_path, improvement)


def _apply_create_file(ontology_path: Path, improvement: dict) -> bool:
    """Create a missing ontology file from template."""
    file_path = Path(improvement["file"])
    if file_path.exists():
        return False

    # Find relative path from ontology dir
    try:
        rel = file_path.relative_to(ontology_path)
    except ValueError:
        rel = file_path.name

    template_content = FILE_TEMPLATES.get(str(rel))
    if not template_content:
        template_content = f"# {rel}\n\n*(auto-created by Neo iteration loop)*\n"

    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(template_content)
    return True


def _apply_fix_empty_yaml(improvement: dict) -> bool:
    """Fix an empty YAML file by adding minimal valid content."""
    file_path = Path(improvement["file"])
    if not file_path.exists():
        return False

    if "entities" in file_path.name:
        file_path.write_text(yaml.dump({"entities": []}, allow_unicode=True))
    elif "rules" in file_path.name:
        file_path.write_text(yaml.dump({"rules": []}, allow_unicode=True))
    elif "relationships" in file_path.name:
        file_path.write_text(yaml.dump({"relationships": []}, allow_unicode=True))
    else:
        file_path.write_text("# Auto-fixed empty file\n")
    return True


def _apply_add_entity_id(improvement: dict) -> bool:
    """Add missing 'id' field to an entity."""
    file_path = Path(improvement["file"])
    if not file_path.exists():
        return False

    data = yaml.safe_load(file_path.read_text())
    if not isinstance(data, dict):
        return False

    changed = False
    for ent in data.get("entities", []):
        if "id" not in ent and "name" in ent:
            ent["id"] = ent["name"].lower().replace(" ", "-").replace("_", "-")
            changed = True

    if changed:
        file_path.write_text(yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False))
    return changed


def _apply_add_rule_severity(improvement: dict) -> bool:
    """Add missing 'severity' field to a rule."""
    file_path = Path(improvement["file"])
    if not file_path.exists():
        return False

    data = yaml.safe_load(file_path.read_text())
    if not isinstance(data, dict):
        return False

    changed = False
    for rule in data.get("rules", []):
        if "severity" not in rule:
            rule["severity"] = "warning"  # Safe default
            changed = True

    if changed:
        file_path.write_text(yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False))
    return changed


# ---------------------------------------------------------------------------
# Improvement identification (Gap Sensing priority order from spec)
# ---------------------------------------------------------------------------

def identify_improvement(ontology_path: Path, past_iterations: list[dict]) -> dict | None:
    """Identify the single highest-impact improvement to make.

    Priority order (from spec section 9.3):
    a. Fix structural failures (free points)
    b. Fill coverage gaps (add missing files)
    c. Improve detection (add rules for uncovered fraud patterns)
    d. Simplify if plateaued
    """
    scores = compute_neo_score(ontology_path)

    if scores["structural"] < 100:
        fix = _find_structural_fix(ontology_path)
        if fix:
            return fix

    if scores["coverage"] < 100:
        fix = _find_coverage_gap(ontology_path)
        if fix:
            return fix

    if scores["detection"] < 100:
        fix = _find_detection_gap(ontology_path)
        if fix:
            return fix

    return _find_simplification(past_iterations)


def _find_structural_fix(ontology_path: Path) -> dict | None:
    """Find a structural issue to fix."""
    entities_dir = ontology_path / "entities"
    if entities_dir.exists():
        for f in entities_dir.glob("*.yaml"):
            try:
                data = yaml.safe_load(f.read_text())
                if not data:
                    return {"type": "structural", "action": "fix_empty_yaml", "file": str(f), "description": f"Fix empty YAML file {f.name}"}
                entities = data.get("entities", []) if isinstance(data, dict) else []
                for ent in entities:
                    if "id" not in ent:
                        return {"type": "structural", "action": "add_entity_id", "file": str(f), "description": f"Add missing 'id' to entity in {f.name}"}
            except yaml.YAMLError:
                return {"type": "structural", "action": "fix_yaml_syntax", "file": str(f), "description": f"Fix YAML syntax error in {f.name}"}

    rules_dir = ontology_path / "rules"
    if rules_dir.exists():
        for f in rules_dir.glob("*.yaml"):
            try:
                data = yaml.safe_load(f.read_text())
                rules = data.get("rules", []) if isinstance(data, dict) else []
                for rule in rules:
                    if "severity" not in rule:
                        return {"type": "structural", "action": "add_rule_severity", "file": str(f), "rule_id": rule.get("id", "unknown"), "description": f"Add missing 'severity' to rule {rule.get('id', 'unknown')}"}
            except yaml.YAMLError:
                return {"type": "structural", "action": "fix_yaml_syntax", "file": str(f), "description": f"Fix YAML syntax error in {f.name}"}

    return None


def _find_coverage_gap(ontology_path: Path) -> dict | None:
    """Find a missing ontology file to create."""
    expected = {
        "ONTOLOGY.md": "ontology overview",
        "INVENTORY.md": "data sources catalog",
        "entities/core-entities.yaml": "core entities",
        "entities/relationships.yaml": "entity relationships",
        "rules/fraud-detection-rules.yaml": "fraud detection rules",
        "skills/verify-bank-statement.md": "verification skill",
        "skills/learn-and-update.md": "learning feedback skill",
        "docs/gaps.md": "knowledge gaps",
        "docs/contradictions.md": "contradiction register",
    }
    for rel_path, purpose in expected.items():
        full_path = ontology_path / rel_path
        if not full_path.exists():
            return {"type": "coverage", "action": "create_file", "file": str(full_path), "purpose": purpose, "description": f"Create missing {rel_path} ({purpose})"}
    return None


def _find_detection_gap(ontology_path: Path) -> dict | None:
    """Find a known fraud pattern not covered by any rule."""
    rule_ids: set[str] = set()
    rules_dir = ontology_path / "rules"
    if rules_dir.exists():
        for f in rules_dir.glob("*.yaml"):
            try:
                data = yaml.safe_load(f.read_text())
                for rule in data.get("rules", []):
                    rule_ids.add(rule.get("id", ""))
            except (yaml.YAMLError, AttributeError):
                pass

    # Patterns with expected rules that are missing
    for pattern in KNOWN_FRAUD_PATTERNS:
        expected = pattern["expected_rule"]
        if expected is not None and expected not in rule_ids:
            return {
                "type": "detection", "action": "add_rule",
                "pattern_id": pattern["id"], "expected_rule_id": expected,
                "severity": pattern["severity"],
                "description": f"Add rule '{expected}' to detect: {pattern['description']}",
            }

    # Patterns with no expected rule (gaps that need new rules)
    for pattern in KNOWN_FRAUD_PATTERNS:
        if pattern["expected_rule"] is None:
            return {
                "type": "detection", "action": "design_new_rule",
                "pattern_id": pattern["id"], "severity": pattern["severity"],
                "description": f"Design new rule for: {pattern['description']}",
            }

    return None


def _find_simplification(past_iterations: list[dict]) -> dict | None:
    """Suggest simplification if plateaued."""
    if len(past_iterations) >= 3:
        recent = past_iterations[-3:]
        scores = [float(it.get("neo_score", 0)) for it in recent]
        if max(scores) - min(scores) < 2.0:
            return {"type": "simplify", "action": "review_for_removal", "description": "Score plateau — review for removable elements"}
    return None


# ---------------------------------------------------------------------------
# Iteration log I/O
# ---------------------------------------------------------------------------

def read_iterations(tsv_path: Path) -> list[dict]:
    """Read iterations.tsv into a list of dicts."""
    if not tsv_path.exists():
        return []
    rows = []
    with open(tsv_path, "r") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            rows.append(row)
    return rows


def append_iteration(tsv_path: Path, iteration: dict) -> None:
    """Append one row to iterations.tsv."""
    fieldnames = ["iteration", "commit", "neo_score", "detection", "structural", "coverage", "coherence", "status", "description"]
    write_header = not tsv_path.exists() or tsv_path.stat().st_size == 0
    with open(tsv_path, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
        if write_header:
            writer.writeheader()
        writer.writerow(iteration)


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------

def git_commit(workspace: Path, message: str) -> str:
    """Stage all workspace changes and commit. Returns short hash."""
    subprocess.run(["git", "add", "-A"], cwd=workspace, capture_output=True)
    result = subprocess.run(["git", "commit", "-m", message], cwd=workspace, capture_output=True, text=True)
    if result.returncode != 0:
        return "no-change"
    hash_result = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=workspace, capture_output=True, text=True)
    return hash_result.stdout.strip()


def git_revert(workspace: Path) -> None:
    """Revert the last commit."""
    subprocess.run(["git", "reset", "--hard", "HEAD~1"], cwd=workspace, capture_output=True)


# ---------------------------------------------------------------------------
# The Loop — ACTUALLY MODIFIES FILES
# ---------------------------------------------------------------------------

def run_iteration_loop(
    workspace: Path,
    max_iterations: int = 5,
    plateau_threshold: int = 10,
    on_progress: callable | None = None,
) -> list[dict]:
    """Run the autoresearch iteration loop.

    This ACTUALLY modifies ontology files, evaluates, and keeps/reverts.

    Args:
        workspace: Path to domain workspace (e.g., workspaces/finance-and-banking/)
        max_iterations: Max iterations before stopping
        plateau_threshold: Consecutive reverts before stopping
        on_progress: Callback for status updates

    Returns:
        List of iteration result dicts
    """
    ontology_path = workspace / "ontology"
    tsv_path = workspace / "iterations.tsv"
    past = read_iterations(tsv_path)

    # Baseline
    baseline_scores = compute_neo_score(ontology_path)
    current_score = baseline_scores["neo_score"]

    if not past:
        commit_hash = git_commit(workspace, "neo-iter-0: baseline")
        append_iteration(tsv_path, {
            "iteration": 0, "commit": commit_hash,
            "neo_score": baseline_scores["neo_score"],
            "detection": baseline_scores["detection"],
            "structural": baseline_scores["structural"],
            "coverage": baseline_scores["coverage"],
            "coherence": baseline_scores["coherence"],
            "status": "baseline", "description": "Initial ontology state",
        })
        past = read_iterations(tsv_path)
        if on_progress:
            on_progress(f"Baseline: neo_score={current_score:.2f} (det={baseline_scores['detection']:.0f} struct={baseline_scores['structural']:.0f} cov={baseline_scores['coverage']:.0f} coh={baseline_scores['coherence']:.0f})")

    consecutive_reverts = 0
    results = []
    attempted_descriptions: set[str] = set()

    for i in range(1, max_iterations + 1):
        iteration_num = len(past) + len(results)

        # Step 1: Identify improvement (skip already-attempted ones)
        improvement = None
        for _ in range(20):  # safety limit on retries
            candidate = identify_improvement(ontology_path, past + results)
            if candidate is None:
                break
            if candidate["description"] not in attempted_descriptions:
                improvement = candidate
                break
            attempted_descriptions.add(candidate["description"])

        if improvement is None:
            if on_progress:
                on_progress(f"Iteration {i}: No more improvements found. Final score={current_score:.2f}")
            break

        attempted_descriptions.add(improvement["description"])

        if on_progress:
            on_progress(f"Iteration {i}: {improvement['description']}")

        # Step 2: APPLY the change (actually write files)
        changed = apply_improvement(ontology_path, improvement)

        if not changed:
            if on_progress:
                on_progress(f"  → Could not apply (no template or already exists). Skipping.")
            # Log as skipped, don't count as revert
            row = {
                "iteration": iteration_num, "commit": "skipped",
                "neo_score": current_score,
                "detection": baseline_scores["detection"],
                "structural": baseline_scores["structural"],
                "coverage": baseline_scores["coverage"],
                "coherence": baseline_scores["coherence"],
                "status": "skipped", "description": improvement["description"],
            }
            append_iteration(tsv_path, row)
            results.append(row)
            continue

        # Step 3: Eval after change
        new_scores = compute_neo_score(ontology_path)
        new_score = new_scores["neo_score"]

        # Step 4: Decision — keep or revert
        if new_score > current_score:
            status = "kept"
            commit_hash = git_commit(workspace, f"neo-iter-{iteration_num}: {improvement['description']}")
            current_score = new_score
            consecutive_reverts = 0
            if on_progress:
                on_progress(f"  → KEPT. neo_score: {current_score:.2f} → {new_score:.2f} (+{new_score - current_score + (new_score - current_score):.2f})")
        elif new_score == current_score:
            # Same score — keep if it's a simplification or structural fix
            status = "kept"
            commit_hash = git_commit(workspace, f"neo-iter-{iteration_num}: {improvement['description']}")
            consecutive_reverts = 0
            if on_progress:
                on_progress(f"  → KEPT (same score, structural improvement). neo_score={new_score:.2f}")
        else:
            status = "reverted"
            git_revert(workspace)
            commit_hash = "reverted"
            consecutive_reverts += 1
            if on_progress:
                on_progress(f"  → REVERTED. neo_score would drop {current_score:.2f} → {new_score:.2f}")

        # Step 5: Log
        row = {
            "iteration": iteration_num, "commit": commit_hash,
            "neo_score": new_scores["neo_score"],
            "detection": new_scores["detection"],
            "structural": new_scores["structural"],
            "coverage": new_scores["coverage"],
            "coherence": new_scores["coherence"],
            "status": status, "description": improvement["description"],
        }
        append_iteration(tsv_path, row)
        results.append(row)

        # Step 6: Plateau check
        if consecutive_reverts >= plateau_threshold:
            if on_progress:
                on_progress(f"Plateau: {consecutive_reverts} consecutive reverts. Stopping.")
            break

    return results


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    """Run iteration loop from command line."""
    import argparse
    parser = argparse.ArgumentParser(description="Neo Autoresearch Iteration Loop")
    parser.add_argument("workspace", help="Path to domain workspace")
    parser.add_argument("--max-iterations", "-n", type=int, default=10, help="Max iterations (default: 10)")
    parser.add_argument("--plateau", type=int, default=10, help="Consecutive reverts to stop (default: 10)")
    args = parser.parse_args()

    workspace = Path(args.workspace)
    if not workspace.exists():
        print(f"Error: Workspace not found: {workspace}", file=sys.stderr)
        sys.exit(1)

    def on_progress(msg: str):
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"[{ts}] {msg}")

    print(f"Neo Autoresearch Loop — {workspace}")
    print("━" * 50)
    results = run_iteration_loop(
        workspace=workspace,
        max_iterations=args.max_iterations,
        plateau_threshold=args.plateau,
        on_progress=on_progress,
    )

    print("━" * 50)
    kept = sum(1 for r in results if r["status"] == "kept")
    reverted = sum(1 for r in results if r["status"] == "reverted")
    skipped = sum(1 for r in results if r["status"] == "skipped")
    print(f"Done: {len(results)} iterations — {kept} kept, {reverted} reverted, {skipped} skipped")
    if results:
        final = max(results, key=lambda r: float(r.get("neo_score", 0)))
        print(f"Best neo_score: {final['neo_score']}")


if __name__ == "__main__":
    main()
